version: '3.3'

services:
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: muchpasswordmanyentropy
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./wp-content:/var/www/html/wp-content
        ports:
            - 80:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress